# Generated by Django 2.2.1 on 2019-05-22 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miscore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(max_length=30)),
                ('projectDesc', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='activityProject',
            field=models.ForeignKey(default="1", on_delete=django.db.models.deletion.CASCADE, related_name='projectname', to='miscore.Project'),
            preserve_default=False,
        ),
    ]
