# Generated by Django 2.2.1 on 2019-05-13 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miscore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activityTypeName', models.CharField(max_length=50)),
                ('activityTypeDesc', models.TextField()),
            ],
        ),
    ]
