# Generated by Django 2.2.1 on 2019-05-25 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miscore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activityType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activityTypeFk', to='miscore.ActivityType'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activityTypeIdentifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activityTypeIdentifierNameFk', to='miscore.ActivityTypeIdentifier'),
        ),
        migrations.AlterField(
            model_name='activitytypeidentifier',
            name='activityType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activityTypeNameFk', to='miscore.ActivityType'),
        ),
    ]
