# Generated by Django 2.2.1 on 2019-05-15 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('miscore', '0002_activitytype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activityDescription', models.TextField()),
                ('activityStartTime', models.DateTimeField()),
                ('activityEndTime', models.DateTimeField()),
                ('activityType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activitytype', to='miscore.ActivityType')),
                ('activityUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
