# Generated by Django 2.2.1 on 2019-05-27 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miscore', '0002_auto_20190525_0900'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bug',
        ),
    ]
