# Generated by Django 2.2.1 on 2019-05-16 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miscore', '0003_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='activityUser',
        ),
    ]
