# Generated by Django 2.2.1 on 2019-05-31 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miscore', '0003_delete_bug'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitytypeidentifier',
            name='activityTypeIdentifierSubCat',
            field=models.CharField(default='trail', max_length=100),
            preserve_default=False,
        ),
    ]
