# Generated by Django 2.2.1 on 2019-06-13 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miscore', '0004_activitytypeidentifier_activitytypeidentifiersubcat'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activityHours',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
