# Generated by Django 2.2.1 on 2019-06-27 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miscore', '0005_activity_activityhours'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardNo', models.CharField(max_length=100)),
                ('workGroup', models.CharField(max_length=100)),
                ('empCode', models.CharField(max_length=100)),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('firstIn', models.DateTimeField()),
                ('lastOut', models.DateTimeField()),
                ('totalHours', models.CharField(max_length=100)),
                ('companyName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=100)),
                ('month', models.CharField(max_length=100)),
                ('fileName', models.CharField(max_length=100)),
                ('timeOfUpload', models.DateTimeField()),
                ('hashofFile', models.CharField(max_length=200)),
                ('fileBase64', models.TextField()),
            ],
        ),
    ]
