# Generated by Django 2.2.1 on 2019-07-10 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miscore', '0008_profile_profilepic'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='projectsInvolved',
            field=models.ManyToManyField(to='miscore.Project'),
        ),
    ]
