# Generated by Django 2.2.1 on 2019-07-13 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miscore', '0009_profile_projectsinvolved'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='activitiesInvolved',
            field=models.ManyToManyField(to='miscore.ActivityType'),
        ),
    ]
