# Generated by Django 2.2.1 on 2019-07-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miscore', '0010_project_activitiesinvolved'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='projectPic',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
