# Generated by Django 2.2.1 on 2019-07-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miscore', '0011_project_projectpic'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitytype',
            name='activityTypeRequired',
            field=models.CharField(default='N', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='projectName',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
