# Generated by Django 2.2.1 on 2019-07-18 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miscore', '0012_auto_20190716_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitytype',
            name='activityTypeName',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='activitytypeidentifier',
            name='activityTypeIdentifierName',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
